# fly.toml app configuration file generated for masa-madre-chatbot on 2025-08-21T11:15:18-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'masa-madre-chatbot'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'false'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
